app01/urls.py
from django.conf.urls import url

from app01 import views
urlpatterns = [
    url(r'^user/$', views.users),
    url(r'^user/(\d+)/$', views.users),
    url(r'^user/search/$', views.search),
    url(r'^user/delete/(\d+)/$', views.delete),
    url(r'^user/delete_all/$', views.delete_all),
    url(r'^user/edit/$', views.edit),
    url(r'^user/add/$', views.add),
    url(r'^user/check_user/$', views.check_user),
]

vail_admin/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app01 import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', views.index),
    url(r'^', include("app01.urls")),
    url(r'^', include("goods.urls")),
    # url(r'^', include("goods.urls")),
    url(r'^login/$', views.login),
]

goods/models.py
from django.db import models
from rbac.models import *

# Create your models here.
class TypeGoods(models.Model):
    title = models.CharField(max_length=64)
    isDelete = models.BooleanField(default=False)
    def __str__(self):
        return self.title

class Goods(models.Model):
    title = models.CharField(max_length=64)

    jianjie = models.CharField(max_length=300)
    bid_price = models.DecimalField(max_digits=8,decimal_places=2,default=0,verbose_name="进价")
    bid_num = models.IntegerField(verbose_name="进货数量")
    goods_data = models.DateTimeField(default = timezone.now,verbose_name="日期")
    bid_money = models.DecimalField(max_digits=8,decimal_places=2,verbose_name="进货总价")
    sale_price = models.DecimalField(max_digits=8,decimal_places=2,verbose_name="售价")
    sale_num = models.IntegerField(verbose_name="销售数量")
    sale_money = models.DecimalField(max_digits=8, decimal_places=2,verbose_name="销售总价")
    kuncui = models.IntegerField()
    unit = models.CharField(max_length=20,verbose_name="单位")
    actual_paymen = models.DecimalField(max_digits=9, decimal_places=2,verbose_name="实付款",default=0)
    goods_expense = models.DecimalField(max_digits=6, decimal_places=2,verbose_name="运费",default=0)
    profit = models.DecimalField(max_digits=9, decimal_places=2,verbose_name="利润",default=0)
    typegoods = models.ForeignKey(to="TypeGoods")
    def __str__(self):
        return self.title

class Company(models.Model):
    name = models.CharField(max_length=64)
    contact = models.CharField(max_length=32)
    company_address = models.CharField(max_length=128)
    receive_address = models.CharField(max_length=128)
    receiver = models.CharField(max_length=32)
    contact_phone = models.CharField(max_length=128)
    receiver_phone = models.CharField(max_length=128)
    def __str__(self):
        return self.name


class OrderInfo(models.Model):
    order_num = models.CharField(max_length=32)
    order_date = models.DateTimeField()
    order_state = models.CharField(max_length=128)
    order_money = models.DecimalField(max_digits=9,decimal_places=2,verbose_name="订单金额")
    actual_paymen = models.DecimalField(max_digits=9,decimal_places=2,verbose_name="实付款",default=0)
    order_expense = models.DecimalField(max_digits=6,decimal_places=2,verbose_name="运费",default=0)
    order_orther = models.DecimalField(max_digits=7,decimal_places=2,verbose_name="其他支出",default=0)
    profit = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="利润",default=0)
    userinfo = models.ForeignKey(UserInfo)
    company = models.ForeignKey(Company)
    goods = models.ManyToManyField(Goods)
    def __str__(self):
        return self.order_num + "  >>>  "+self.company.name
    

templates/x-admin/add-member.html
{% extends "x-admin/base.html" %}

{% block content %}
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Form Components</h1>
          <p>Bootstrap default form components</p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Forms</li>
          <li class="breadcrumb-item"><a href="#">Form Components</a></li>
        </ul>
      </div>

    <div class="container">


        <form class="form-horizontal" method="post" action="/user/add/">
            {% csrf_token %}
            <div class="form-group ">
                <label for="" class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-4">
                    <input type="text" name="username" class="form-control" id="username" placeholder="请输入用户名">
                    <span id="helpBlock2" class="help-block"></span>
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
                <div class="col-sm-4">
                    <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                    <span id="helpBlock2" class="help-block"></span>
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">确认密码</label>
                <div class="col-sm-4">
                    <input type="password" name="repassword" class="form-control" id="repassword" placeholder="Password">
                    <span id="helpBlock2" class="help-block"></span>
                </div>
            </div>
            <div class="form-group ">
                <label for="" class="col-sm-2 control-label">电话</label>
                <div class="col-sm-4">
                    <input type="text" name="phone" class="form-control" id="phone" placeholder="请输入电话">
                    <span id="helpBlock2" class="help-block"></span>
                </div>
            </div>
             <div class="form-group ">
                <label for="" class="col-sm-2 control-label">邮箱</label>
                <div class="col-sm-4">
                    <input type="email" name="email" class="form-control" id="email" placeholder="请输入邮箱">
                    <span id="helpBlock2" class="help-block"></span>
                </div>
            </div>
             <div class="form-group ">
                <label for="" class="col-sm-2 control-label">身份证</label>
                <div class="col-sm-4">
                    <input type="text" name="card_id" class="form-control" id="card_id" placeholder="请输入身份证号码">
                    <span id="helpBlock2" class="help-block"></span>
                </div>
            </div>
             <div class="form-group ">
                <label for="" class="col-sm-2 control-label">地址</label>
                <div class="col-sm-4">
                    <input type="text" name="address" class="form-control" id="address" placeholder="请输入住址">
                    <span id="helpBlock2" class="help-block"></span>
                </div>
            </div>
            <div class="form-group ">
                <label for="" class="col-sm-2 control-label">入职时间</label>
                <div class="col-sm-4">
                    <input type="date" name="entry_time" class="form-control" id="entry_time">
                    <span id="helpBlock2" class="help-block"></span>
                </div>
            </div>
            <div class="form-group ">
                <label for="" class="col-sm-2 control-label">状态</label>
                <div class="col-sm-4">
                    <select class="form-control" style="padding: 0" name="state" id="state">
                        {% for state in state_choices%}
                        <option value="{{ state.0 }}" >{{ state.1 }}</option>
                       {% endfor %}
                    </select>
                <span id="helpBlock2" class="help-block"></span>
                </div>
            </div>
            <div class="form-group ">
                <label for="" class="col-sm-2 control-label">职务</label>
                <div class="col-sm-4">
                    <select class="form-control" style="padding: 0" name="roles" id="role" multiple>
                        {% for role in role_list%}
                        <option value="{{ role.id }}">{{ role.title }}</option>
                       {% endfor %}
                    </select>
                <span id="helpBlock2" class="help-block"></span>
                </div>
            </div>
            <div class="form-group ">
                <label for="" class="col-sm-2 control-label">性别</label>
                <div class="col-sm-2" id="gender">
                    {% for gender in gender_choices %}

                    <label class="radio-inline">

                        <input type="radio" name="gender" id="{{ gender.0 }}" value="{{ gender.0 }}"> {{ gender.1 }}
                    </label>

                    {% endfor %}


                </div>
            <div class="col-sm-2" id="helpBlock2" class="help-block"></div>


            </div>


            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default" id="button">添加</button>
                </div>
            </div>

            </form>

    </div>
    <script src="../../static/js/jquery-3.2.1.min.js"></script>
    <script>

    $(function () {
        var error_name = false;
        var error_password = false;
        var error_repassword = false;
        var error_phone =false;
        var error_email = false;
        var error_card = false;
        var error_address = false;
        var error_entry_time = false;
        var error_state = false;
        var error_role = false;
        var error_gender = false;

        $("#username").blur(function () {
            check_username();
        });
        $("#password").blur(function () {
            check_pwd();
        });
        $("#repassword").blur(function () {
            check_repwd();
        });
        $("#phone").blur(function () {
            check_phone();
        });
        $("#email").blur(function () {
            check_email();
        });
        $("#card_id").blur(function () {
            check_card();
        });
        $("#address").blur(function () {
            check_address();
        });

        //检查用户名
        function check_username() {
            var len = $('#username').val().length;
            var username = $("#username").val();

            if(len<2||len>20)
            {
                $('#username').next().html('输入2-20个字符的用户名').css("color","red");
                $('#username').next().show();
                error_name = true;
            }
            else
            {
                //第一种向后端发送请求
            {#    console.log(username)#}
            {#    $.get('/user/check_user/?username='+$('#username').val(),function(data){#}
		    {#    if(data.count == 1){#}
		    {#        console.log(data.count)#}
		    {#        $('#username').next().html('用户名已经存在').show().css("color","red");#}
		    {#        error_name=true;#}
		    {#    }else{#}
			{#        $('#username').next().hide();#}
			{#        error_name = false;#}
		    {#    }#}
		    {#});#}
                //第二种向后端发送请求
                console.log(username)
                $.ajax({
                    url:"/user/check_user/",
                    type:"get",
                    data:{"username":username},
                    success:function (data) {
                        if(data.count == 1){
                            console.log(data.count)
                            $('#username').next().html('用户名已存在,请重新输入').css("color","red").show();
                            error_name = true;
                        }else {
                            $('#username').next().hide();
                            error_name = false;
                        }

                    }
                });

            }
            };

        //检查密码
        function check_pwd() {
            var len = $('#password').val().length;
            if(len<6||len>20)
            {
                $('#password').next().html('密码最少6位，最长20位').css("color","red");
                $('#password').next().show();
                error_password = true;
            }
            else
            {
                $('#password').next().hide();
                error_password = false;
            }
        };
        //检查重复密码
        function check_repwd() {
            var pass = $('#password').val();
            var cpass = $('#repassword').val();

            if(pass!=cpass)
            {
                $('#repassword').next().html('两次输入的密码不一致').css("color","red");
                $('#repassword').next().show();
                error_repassword = true;
            }
            else
            {
                $('#repassword').next().hide();
                error_repassword = false;
            }

        };
        //检查手机号
        function check_phone() {
            var phone = $("#phone").val();
            if(!(/^1[3|4|5|6|7|8|9][0-9]\d{8}$/.test(phone))){

                //以1开头，3-9第二位，第三位0-9，剩下八位
                $("#phone").next().html("手机号码格式不正确").css("color","red");
                error_phone = true;

            }else {
                $("#phone").next().hide();
                error_phone = false;
            }

        };

        //检查邮箱
        function check_email() {
		var re = /^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$/;

		if(re.test($('#email').val()))
		{
			$('#email').next().hide();
			error_email = false;
		}
		else
		{
			$('#email').next().html('你输入的邮箱格式不正确').css("color","red");
			$('#email').next().show();
			error_email = true;
		}

	    };
        //检查身份证
        function check_card() {
            var card = $("#card_id").val();
            var reg = /(^\d{15}$)|(^\d{17}(\d|X|x)$)/;
            if(reg.test(card) === false){
                $('#card_id').next().html('你输入的身份证格式不正确').css("color","red");
                $('#card_id').next().show();
                error_card = true;
            }else{
                $('#card_id').next().hide();
			    error_card = false;

            }
        };
        // //检验地址是否有值#
        function check_address() {
            var address = $("#address").val()
            if(address){
                $('#address').next().hide();
                error_address = false;
            }else {
                $('#address').next().html('请输入地址').css("color","red");
                $('#address').next().show();
                error_address = true;
            }

        };

        $("#button").click(function () {
            check_username();
            check_pwd();
            check_repwd();
            check_phone();
            check_email();
            check_card();
            check_address();


            var entry_time = $("#entry_time").val();
            var state = $("#state").val();
            var role = $("#role").val();
            var gender = $('input:radio:checked');
            console.log(entry_time,state,role,gender)
            if(entry_time.length == 0){
                $('#entry_time').next().html('请选择日期').css("color","red");
                $('#entry_time').next().show();
                error_entry_time = true
                console.log("-------")
                console.log(error_entry_time)
            }else{
                $('#entry_time').next().hide();
                error_entry_time = false
                console.log(error_entry_time)

            };
            if(state.length == 0){
                $('#state').next().html('请选择状态').css("color","red");
                $('#state').next().show();
                error_state = true
            }else{
                $('#state').next().hide();
                error_state = false


            };
            if(role.length == 0){
                $('#role').next().html('请选择职务').css("color","red");
                $('#role').next().show();
                error_role = true
            }else{
                $('#role').next().hide();
                error_role = false
            };
            if(gender.length == 0){
                $('#gender').next().html('请选择性别').css("color","red");
                $('#gender').next().show();
                error_gender = true
            }else{
                $('#gender').next().hide();
                error_gender = false
            };
            if(error_name == false && error_password == false &&
                error_repassword == false && error_phone == false &&　
                error_email == false && error_card == false && error_address == false &&
                error_entry_time == false && error_state == false && error_role == false && error_gender == false){
                console.log("数据都正确")
                console.log(error_gender)
                return true;
            }else {
                console.log("数据有错误")
                console.log(error_gender)
                return false;
            }


        })
        })

//先blue调用检测函数，显示错误，最后点击提交的时候，再次调用函数来确定数据是否正确，双重作用
    </script>


{% endblock %}

templates/x-admin/goods-list.html
{% extends "x-admin/base.html" %}

{% block content %}
    <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Form Components</h1>
          <p>Bootstrap default form components</p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Forms</li>
          <li class="breadcrumb-item"><a href="#">Form Components</a></li>
        </ul>
      </div>

        <select class="form-control col-md-1" style="height: 34px;margin: 8px 10px 0 0" onchange="window.location=this.value" name="select">
            <option value="" selected="selected">选择每页数据</option>
            <option value="/goods/5/">每页5条数据-</option>
            <option value="/goods/10/">每页10条数据</option>
            <option value="/goods/20/">每页20条数据</option>
            <option value="/goods/30/">每页30条数据</option>
            <option value="/goods/50/">每页50条数据</option>
            <option value="/goods/100/">每页100条数据</option>
            <option value="/goods/200/">每页200条数据</option>
            <option value="/goods/500/">每页500条数据</option>
        </select>

        <a type="button" class="btn btn-primary form-inline pull-left" href="/goods/add/" style="margin-top: 8px"
           id="add">添加</a>
        <button type="button" class="btn btn-primary form-inline pull-left" id="excell" onclick="method5('dataTable')"
                style="margin:8px 0 0 10px">导出表格
        </button>

        <form class="navbar-form navbar-left form-inline" method="post" action="/goods/search/">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="title" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-primary">搜索</button>
        </form>
        <button type="button" class="btn btn-danger form-inline pull-right" style="margin-top: 8px" id="delete_all">
            批量删除
        </button>


<table class="table table-bordered" id="dataTable">
      <thead>
        <tr>
         <th>ID</th>
            <th>名称</th>
            <th>型号</th>
            <th>单位</th>
            <th>进价</th>
            <th>进货数量</th>
            <th>进货总价</th>
            <th>售价</th>
            <th>售货数量</th>
            <th>售货总价</th>
            <th>日期</th>
            <th>库存</th>
            <th>运费</th>
            <th>实付款</th>
            <th>利润</th>
             <th>订货公司</th>
            <th>操作</th>

            <th><input id="choice" type="checkbox"></th>
            <th>备注</th>
        </tr>
      </thead>
      <tbody>
       {% for goods in goods_list %}
        <tr class="row1">

          <th>{{ forloop.counter }}</th>
          <th>{{ goods.typegoods.title}}</th>
          <td>{{ goods.title }}</td>

          <td>{{ goods.unit }}</td>
          <td>{{ goods.bid_price }}</td>
            <td>{{ goods.bid_num }}</td>
            <td>{{ goods.bid_money }}</td>
            <td>{{ goods.sale_price }}</td>
            <td>{{ goods.sale_num }}</td>
            <td>{{ goods.sale_money }}</td>
            <td>{{ goods.goods_data|date:'Y-m-d H:i:s' }}</td>
            <td>{{ goods.kuncui }}</td>
            <td>{{ goods.goods_expense }}</td>
            <td>{{ goods.actual_paymen }}</td>
           <td>{{ goods.profit}}</td>
           {% for order in goods.orderinfo_set.all %}

           <td><a href="">{{ order.company.name }}</a></td>
               {% empty %}
                <td></td>

           {% endfor %}


            <td style="padding: 10px"><p style="margin: 0px">
              <a type="button" class="btn btn-primary btn-sm" href="/goods/edit/?id={{goods.id}}" style="margin: 0px;padding: 0px">编辑</a>
              <a type="button" class="btn btn-danger btn-sm" href="/goods/delete/{{ goods.pk }}/" style="margin: 0px;padding: 0px">删除</a>
            </p></td>
           <td><input class ="choice_item" type="checkbox" name="check" value="{{ goods.pk }}" ></td>
           <td>{{ goods.jianjie}}</td>
            {% endfor %}

        </tr>

      </tbody>
    </table>
    <nav class="pull-right">
<ul class="pagination" style="margin-top: 0px" >
   {{ pagination.page_html|safe }}
</ul>
</nav>
 <script>
    //批量删除
   $("#choice").click(function () {

     if($(this).prop("checked")){
           $(".choice_item").prop("checked",true)
     }else {
           $(".choice_item").prop("checked",false)
     }

   });


   $('#delete_all').click(function() {
       var check_val = [];//定义一个空数组
       var url = window.location.href;  //获取当前页面网址
       console.log(url)
       $("input[name='check']:checked").each(function (i) {//把所有被选中的复选框的值存入数组
           check_val[i] = $(this).val();

   });
       {#发送ajax请求内层外层问题，内层出现多次ajax请求，外层一次#}
       check_val.unshift(url);//把当前页面网址添加到check_val中，发回后端
       console.log(check_val);
       $.ajax({
       url:'/user/delete_all/',
       type:'get',
       data:{"user_id":JSON.stringify(check_val)},
       success:function (data) {
           console.log(data);
           location.href = data.url;

       }
   })


   });

   //打印表格
        var idTmr;

        function getExplorer() {
            var explorer = window.navigator.userAgent;
            //ie
            if(explorer.indexOf("MSIE") >= 0) {
                return 'ie';
            }
            //firefox
            else if(explorer.indexOf("Firefox") >= 0) {
                return 'Firefox';
            }
            //Chrome
            else if(explorer.indexOf("Chrome") >= 0) {
                return 'Chrome';
            }
            //Opera
            else if(explorer.indexOf("Opera") >= 0) {
                return 'Opera';
            }
            //Safari
            else if(explorer.indexOf("Safari") >= 0) {
                return 'Safari';
            }
        }

        function method5(tableid) {
            if(getExplorer() == 'ie') {
                var curTbl = document.getElementById(tableid);
                var oXL = new ActiveXObject("Excel.Application");
                var oWB = oXL.Workbooks.Add();
                var xlsheet = oWB.Worksheets(1);
                var sel = document.body.createTextRange();
                sel.moveToElementText(curTbl);
                sel.select();
                sel.execCommand("Copy");
                xlsheet.Paste();
                oXL.Visible = true;

                try {
                    var fname = oXL.Application.GetSaveAsFilename("Excel.xls",
                        "Excel Spreadsheets (*.xls), *.xls");
                } catch(e) {
                    print("Nested catch caught " + e);
                } finally {
                    oWB.SaveAs(fname);
                    oWB.Close(savechanges = false);
                    oXL.Quit();
                    oXL = null;
                    idTmr = window.setInterval("Cleanup();", 1);
                }

            } else {
                tableToExcel(tableid)
            }
        }

        function Cleanup() {
            window.clearInterval(idTmr);
            CollectGarbage();
        }
        var tableToExcel = (function() {
            var uri = 'data:application/vnd.ms-excel;base64,',
                template = '<html><head><meta charset="UTF-8"></head><body><table  border="1">{table}</table></body></html>',
                base64 = function(
                    s) {
                    return window.btoa(unescape(encodeURIComponent(s)))
                },
                format = function(s, c) {
                    return s.replace(/{(\w+)}/g, function(m, p) {
                        return c[p];
                    })
                }
            return function(table, name) {
                if(!table.nodeType)
                    table = document.getElementById(table)
                var ctx = {
                    worksheet: name || 'Worksheet',
                    table: table.innerHTML
                }
                window.location.href = uri + base64(format(template, ctx))
            }
        })()

</script>
{% endblock %}

templates/x-admin/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Main CSS-->
    <link rel="stylesheet" type="text/css" href="../../static/css/main.css">
    <!-- Font-icon css-->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Login - LBC Admin</title>
  </head>
  <body>
    <section class="material-half-bg">
      <div class="cover"></div>
    </section>
    <section class="login-content">
      <div class="logo">
        <h1>LBCTECH</h1>
      </div>
      <div class="login-box">
        <form class="login-form" action="" method="post">
            {% csrf_token %}
          <h3 class="login-head"><i class="fa fa-lg fa-fw fa-user"></i>SIGN IN</h3>
          <div class="form-group" >
            <label class="control-label">USERNAME</label>
            <input class="form-control" name="username" type="text" placeholder="Email" autofocus>
          </div>
          <div class="form-group">
            <label class="control-label">PASSWORD</label>
            <input class="form-control" name="password" type="password" placeholder="Password">
          </div>
          <div class="form-group">
            <div class="utility">
              <div class="animated-checkbox">
                <label>
                  <input type="checkbox"><span class="label-text">Stay Signed in</span>
                </label>
              </div>
              <p class="semibold-text mb-2"><a href="#" data-toggle="flip">Forgot Password ?</a></p>
            </div>
          </div>
          <div class="form-group btn-container">
            <button class="btn btn-primary  btn-block" type="submit"><i class="fa fa-sign-in fa-lg fa-fw"></i>SIGN IN</button>
          </div>
        </form>
        <form class="forget-form" action="#">
          <h3 class="login-head"><i class="fa fa-lg fa-fw fa-lock"></i>Forgot Password ?</h3>
          <div class="form-group">
            <label class="control-label">EMAIL</label>
            <input class="form-control" type="text" placeholder="Email">
          </div>
          <div class="form-group btn-container">
            <button class="btn btn-primary btn-block"><i class="fa fa-unlock fa-lg fa-fw"></i>RESET</button>
          </div>
          <div class="form-group mt-3">
            <p class="semibold-text mb-0"><a href="#" data-toggle="flip"><i class="fa fa-angle-left fa-fw"></i> Back to Login</a></p>
          </div>
        </form>
      </div>
    </section>
    <!-- Essential javascripts for application to work-->
    <script src="../../static/js/jquery-3.2.1.min.js"></script>
    <script src="../../static/js/popper.min.js"></script>
    <script src="../../static/js/bootstrap.min.js"></script>
    <script src="../../static/js/main.js"></script>
    <!-- The javascript plugin to display page loading on top-->
    <script src="../../static/js/plugins/pace.min.js"></script>
    <script type="text/javascript">
      // Login Page Flipbox control
      $('.login-content [data-toggle="flip"]').click(function() {
      	$('.login-box').toggleClass('flipped');
      	return false;
      });
    </script>
  </body>
</html>

templates/x-admin/order-detail.html
{% extends "x-admin/base.html" %}

{% block content %}


<div style="width: 1000px;margin: 0 auto;border: 1px solid ">

<div style="width: 1000px;margin: 0 auto">
    <img src="" alt="">
    <hr style="border: 1px solid">

        <div><h3 style="margin: 0 auto">河南建瓴科技</h3></div>
    <h3>购销合同</h3>

</div>






</div>







{% endblock %}